// AUTO-GENERATED by scripts/migrate-opsd.mjs
// Re-exports all migrated subject data for type-safe imports.

export * from './info_act';
export * from './saraban';
export * from './english';
export * from './general_knowledge';
