/**
 * Industry Data Loader — reads auto-generated TypeScript modules
 *
 * Data is auto-generated by scripts/migrate-industry.mjs from
 * ~/Documents/SlothMove/Page/source/Industry/ (READ-ONLY).
 *
 * Migrated subjects (real data — 5 of 9):
 *   - admin_act            (100 quiz items)
 *   - factory_act          (100 quiz items)
 *   - info_act             (100 quiz items)
 *   - governance           (100 quiz items)
 *   - industrial_strategy  (100 quiz items)
 *
 * Subjects registered in config but with NO source data:
 *   - economic_analysis, english, computer, general_knowledge
 *   These return [] so the UI renders truthful "no data" placeholders.
 *
 * For games whose data hasn't been migrated yet (sorting, order,
 * spelling, truefalse, authority, logic), we return universal sample
 * items — same approach as PAB + OPSD.
 */

import * as IndustryData from './data';
import type { CourseConfig, GameId } from '@/lib/course-types';

type IndustryModule = { [k: string]: any };
const INDUSTRY_MODULES = IndustryData as IndustryModule;

/* -------------------------------------------------------------------------- */
/*                       Sample data for non-migrated games                   */
/*  Industry-flavored universal samples (วิชาอุตสาหกรรม)                     */
/* -------------------------------------------------------------------------- */

const SAMPLE_SORTING = [
  {
    question: 'เรียงลำดับขั้นตอนการขอใบอนุญาตประกอบกิจการโรงงาน',
    items: ['ยื่นคำขอ', 'เจ้าหน้าที่ตรวจสอบเอกสาร', 'ตรวจสถานประกอบการ', 'เสนอผู้มีอำนาจลงนาม', 'ออกใบอนุญาต'],
    explain: 'ขั้นตอนตาม พ.ร.บ. โรงงาน พ.ศ. 2535'
  },
  {
    question: 'เรียงลำดับวงจร PDCA ในงานวิเคราะห์นโยบาย',
    items: ['Plan (วางแผน)', 'Do (ปฏิบัติ)', 'Check (ตรวจสอบ)', 'Act (ปรับปรุง)'],
    explain: 'วงจรบริหารงานคุณภาพ Deming'
  }
];

const SAMPLE_ORDER = [
  {
    question: 'เรียงขั้นตอนการจัดทำแผนยุทธศาสตร์อุตสาหกรรม',
    steps: ['วิเคราะห์สถานการณ์ (SWOT)', 'กำหนดวิสัยทัศน์/พันธกิจ', 'ตั้งเป้าหมาย/ตัวชี้วัด', 'จัดทำแผนงาน/โครงการ', 'เสนอขออนุมัติ', 'นำไปปฏิบัติและติดตาม']
  },
  {
    question: 'เรียงขั้นตอนการวิเคราะห์ผลกระทบสิ่งแวดล้อม (EIA)',
    steps: ['การคัดกรองโครงการ', 'จัดทำรายงาน EIA', 'เปิดรับฟังความคิดเห็น', 'พิจารณารายงานโดย คชก.', 'อนุมัติ/ไม่อนุมัติโครงการ']
  }
];

const SAMPLE_SPELLING = [
  { word: 'อุตสาหกรรม', definition: 'การประกอบกิจการเพื่อผลิตสินค้า/บริการ', hint: 'ขึ้นต้นด้วย อุ' },
  { word: 'โรงงาน', definition: 'สถานที่ผลิตสินค้าอุตสาหกรรม', hint: 'มีคำว่า "งาน" ซ้ำ' },
  { word: 'ยุทธศาสตร์', definition: 'แผนการระยะยาวเพื่อบรรลุเป้าหมาย', hint: 'มี 4 พยางค์' },
  { word: 'ธรรมาภิบาล', definition: 'การบริหารจัดการที่ดี โปร่งใส ตรวจสอบได้', hint: 'ขึ้นต้นด้วย ธ' }
];

const SAMPLE_TRUEFALSE = [
  { statement: 'โรงงานทุกขนาดต้องขอใบอนุญาตประกอบกิจการโรงงาน', answer: false, explain: 'โรงงานจำพวกที่ 1 ได้รับการยกเว้น ไม่ต้องขอใบอนุญาต แต่ต้องแจ้งให้กรมโรงงานทราบ' },
  { statement: 'พ.ร.บ. โรงงานกำหนดให้โรงงานต้องติดตั้งระบบบำบัดน้ำเสีย', answer: true },
  { statement: 'กระทรวงอุตสาหกรรมดูแลเฉพาะโรงงานขนาดใหญ่เท่านั้น', answer: false, explain: 'กระทรวงอุตสาหกรรมดูแลโรงงานทุกขนาดตาม พ.ร.บ. โรงงาน พ.ศ. 2535' },
  { statement: 'ธรรมาภิบาล (Good Governance) เป็นหลักการสำคัญในการบริหารประเทศ', answer: true }
];

const SAMPLE_AUTHORITY: never[] = [];
// Authority/Logic: not migrated for Industry — return [].

/* -------------------------------------------------------------------------- */
/*                            getSubjectData (main API)                       */
/* -------------------------------------------------------------------------- */

export function getSubjectData(
  course: CourseConfig,
  subjectId: string,
  game: GameId
): any[] {
  if (course.id !== 'industry') return [];

  // Quiz + flashcard + match + cloze: data is auto-migrated from Industry source.
  // Other 6 games (sorting/order/spelling/truefalse/authority/logic) are
  // universal samples — same as PAB + OPSD.
  if (game === 'quiz' || game === 'flashcard' || game === 'match' || game === 'cloze') {
    const moduleData = INDUSTRY_MODULES[`${subjectId}_${game}`];
    if (!moduleData || !Array.isArray(moduleData)) return [];
    if (game === 'flashcard') {
      return moduleData.map((c: any) => ({
        front: String(c.front || ''),
        back: String(c.back || '')
      }));
    }
    // quiz / match / cloze — shape already matches the shared types
    return moduleData;
  }

  switch (game) {
    case 'sorting': return SAMPLE_SORTING;
    case 'order': return SAMPLE_ORDER;
    case 'spelling': return SAMPLE_SPELLING;
    case 'truefalse': return SAMPLE_TRUEFALSE;
    case 'authority': return SAMPLE_AUTHORITY;
    case 'logic': return [];
    default:
      return [];
  }
}

export function getSubjectItemCount(subjectId: string, game: GameId): number {
  if (game === 'quiz' || game === 'flashcard' || game === 'match' || game === 'cloze') {
    const data = INDUSTRY_MODULES[`${subjectId}_${game}`];
    return Array.isArray(data) ? data.length : 0;
  }
  // Sample sizes for non-migrated games
  const SAMPLE_SIZES: Partial<Record<GameId, number>> = {
    sorting: 2, order: 2, spelling: 4, truefalse: 4
  };
  return SAMPLE_SIZES[game] ?? 0;
}
