/**
 * OPSD Data Loader — reads auto-generated TypeScript modules
 *
 * Data is auto-generated by scripts/migrate-opsd.mjs from
 * ~/Documents/SlothMove/Page/source/OPSD/ (READ-ONLY).
 *
 * Migrated subjects (real data):
 *   - info_act           (100 quiz items)
 *   - saraban            (150 quiz items)
 *   - english            (315 quiz items)
 *   - general_knowledge  (256 quiz items)
 *
 * Subjects registered in config but with NO source data:
 *   - admin_act, defense_policy, computer
 *   These return [] so the UI can render truthful "no data" placeholders
 *   (see getSubjectData → NoDataView in the game page).
 *
 * For games whose data hasn't been migrated yet (sorting, order,
 * spelling, truefalse, authority, logic), we return universal sample
 * items — same approach as PAB.
 */

import * as OPSDData from './data';
import type { CourseConfig, GameId } from '@/lib/course-types';

type OPSDModule = { [k: string]: any };
const OPSD_MODULES = OPSDData as OPSDModule;

/* -------------------------------------------------------------------------- */
/*                       Sample data for non-migrated games                   */
/*  Mirrors PAB data-loader.ts — universal samples, not per-subject.         */
/* -------------------------------------------------------------------------- */

const SAMPLE_SORTING = [
  {
    question: 'เรียงลำดับสายการบังคับบัญชาในกระทรวงกลาโหมจากบนลงล่าง',
    items: ['รัฐมนตรีว่าการกระทรวงกลาโหม', 'ปลัดกระทรวงกลาโหม', 'เสนาธิการทหารบก', 'ผู้บัญชาการทหารสูงสุด', 'ผู้บังคับกองพัน'],
    explain: 'โครงสร้างบังคับบัญชาของกระทรวงกลาโหม เริ่มจากรัฐมนตรี → ปลัดกระทรวง → เสนาธิการ → ผบ.ทหารสูงสุด → ผบ.กองพัน'
  },
  {
    question: 'เรียงลำดับขั้นตอนการรับหนังสือราชการตามระเบียบสารบรรณ',
    items: ['รับหนังสือจากหน่วยงานภายนอก', 'ลงทะเบียนรับ', 'เสนอผู้บังคับบัญชา', 'สั่งการ/พิจารณา', 'ดำเนินการตามคำสั่ง', 'จัดเก็บเข้าแฟ้ม'],
    explain: 'ขั้นตอนตามระเบียบสำนักนายกรัฐมนตรี ว่าด้วยงานสารบรรณ พ.ศ. 2526'
  }
];

const SAMPLE_ORDER = [
  {
    question: 'เรียงขั้นตอนการออกพระราชบัญญัติ',
    steps: ['สภาผู้แทนฯ พิจารณา', 'วุฒิสภาพิจารณา', 'นายกรัฐมนตรีนำขึ้นทูลเกล้าฯ', 'พระมหากษัตริย์ทรงลงพระปรมาภิไธย', 'ประกาศในราชกิจจานุเบกษา', 'มีผลบังคับใช้']
  },
  {
    question: 'เรียงขั้นตอนการประกาศใช้ระเบียบกระทรวงกลาโหม',
    steps: ['ร่างระเบียบโดยหน่วยงานที่รับผิดชอบ', 'เสนอปลัดกระทรวงกลาโหมพิจารณา', 'รัฐมนตรีว่าการกระทรวงกลาโหมลงนาม', 'ประกาศในราชกิจจานุเบกษา', 'มีผลบังคับใช้']
  }
];

const SAMPLE_SPELLING = [
  { word: 'กลาโหม', definition: 'ชื่อกระทรวงที่ดูแลด้านการทหาร', hint: 'ขึ้นต้นด้วย ก' },
  { word: 'สารบรรณ', definition: 'งานเกี่ยวกับการบริหารเอกสารราชการ', hint: 'มีคำว่า "บรรณ" อยู่ข้างหลัง' },
  { word: 'ข้าราชการ', definition: 'ผู้ที่ทำงานในระบบราชการ', hint: 'เริ่มด้วย ข' },
  { word: 'ยุทธศาสตร์', definition: 'แผนการรบหรือกลยุทธ์ระยะยาว', hint: 'มี 4 พยางค์' }
];

const SAMPLE_TRUEFALSE = [
  { statement: 'พ.ร.บ. ข้อมูลข่าวสารของราชการ พ.ศ. 2540 ให้ใช้บังคับตั้งแต่วันประกาศในราชกิจจานุเบกษา', answer: false, explain: 'จริง ๆ ให้ใช้บังคับเมื่อพ้นกำหนด 90 วันนับแต่วันประกาศในราชกิจจานุเบกษา' },
  { statement: 'หนังสือราชการตามระเบียบสารบรรณมี 6 ชนิด', answer: true },
  { statement: 'กระทรวงกลาโหมมีเฉพาะกองทัพบกเท่านั้น', answer: false, explain: 'กระทรวงกลาโหมมี 3 เหล่าทัพ: บก เรือ อากาศ' },
  { statement: 'ผู้บัญชาการทหารสูงสุดเป็นตำแหน่งสูงสุดของกองทัพไทย', answer: true }
];

const SAMPLE_AUTHORITY: never[] = [];
// Authority/Logic: not migrated for OPSD — return [].

/* -------------------------------------------------------------------------- */
/*                            getSubjectData (main API)                       */
/* -------------------------------------------------------------------------- */

export function getSubjectData(
  course: CourseConfig,
  subjectId: string,
  game: GameId
): any[] {
  if (course.id !== 'opsd') return [];

  // Quiz + flashcard + match + cloze: data is auto-migrated from OPSD source.
  // Other 6 games (sorting/order/spelling/truefalse/authority/logic) are
  // universal samples — same as PAB.
  if (game === 'quiz' || game === 'flashcard' || game === 'match' || game === 'cloze') {
    const moduleData = OPSD_MODULES[`${subjectId}_${game}`];
    if (!moduleData || !Array.isArray(moduleData)) return [];
    if (game === 'flashcard') {
      return moduleData.map((c: any) => ({
        front: String(c.front || ''),
        back: String(c.back || '')
      }));
    }
    // quiz / match / cloze — shape already matches the shared types
    return moduleData;
  }

  switch (game) {
    case 'sorting': return SAMPLE_SORTING;
    case 'order': return SAMPLE_ORDER;
    case 'spelling': return SAMPLE_SPELLING;
    case 'truefalse': return SAMPLE_TRUEFALSE;
    case 'authority': return SAMPLE_AUTHORITY;
    case 'logic': return [];
    default:
      return [];
  }
}

export function getSubjectItemCount(subjectId: string, game: GameId): number {
  if (game === 'quiz' || game === 'flashcard' || game === 'match' || game === 'cloze') {
    const data = OPSD_MODULES[`${subjectId}_${game}`];
    return Array.isArray(data) ? data.length : 0;
  }
  // Sample sizes for non-migrated games
  const SAMPLE_SIZES: Partial<Record<GameId, number>> = {
    sorting: 2, order: 2, spelling: 4, truefalse: 4
  };
  return SAMPLE_SIZES[game] ?? 0;
}
