/**
 * Police Admin — Quiz data (auto-generated by migrate-police-admin.mjs).
 *
 * Real quiz data migrated from
 *   ~/Documents/SlothMove/Page/source/police_admin/<subject>/
 *
 * Each subject exports a `${subjectId}_quiz: QuizItem[]` array:
 *   math (180) + thai (300) + computer (600) + saraban (100) +
 *   law (100) + english (100) = 1,380 items
 *
 * Other game types (flashcard/match/cloze) are derived from quiz data
 * by the data-loader.ts adapters (see quiz-to-games.ts pattern in
 * src/lib/adapters/).
 *
 * Math-specific games (Phase B):
 *   math_analogy, math_series, math_word_problem, math_speed_percent
 *   — generated by scripts/migrate-math-games.mjs from the math
 *   quiz pool, filtered by category/pattern tags.
 */

export { math_quiz } from './math';
export { thai_quiz } from './thai';
export { computer_quiz } from './computer';
export { saraban_quiz } from './saraban';
export { law_quiz } from './law';
export { english_quiz } from './english';

export { math_analogy } from './math_analogy';
export { math_series } from './math_series';
export { math_word_problem } from './math_word_problem';
export { math_speed_percent } from './math_speed_percent';
export { thai_flashcard } from './thai_flashcard';
export { thai_match } from './thai_match';
export { thai_spelling } from './thai_spelling';
export { thai_order } from './thai_order';
export { computer_sorting } from './computer_sorting';
export { saraban_order, saraban_authority, saraban_truefalse, saraban_flashcard, saraban_match, saraban_cloze } from './saraban_practice';
export { law_authority, law_truefalse, law_flashcard } from './law_practice';
export { english_flashcard } from './english_practice';
