// AUTO-GENERATED by scripts/migrate-math-games.mjs — DO NOT EDIT
// Source: ~/Documents/SlothMove/Page/source/police_admin/math/math.questions.js (read-only)
// Derived 20 items from the math quiz pool.

import type { QuizItem } from "../../../lib/course-types";

export const math_series: QuizItem[] = [
  {
    "question": "A  C  E  G  ...",
    "choices": [
      "H",
      "I",
      "J",
      "K"
    ],
    "answer": 1,
    "explanation": "ตัวอักษรเพิ่มทีละ <strong>2</strong> ตำแหน่ง<br>A → C → E → G → <strong>I</strong>",
    "hint": "ข้ามตัวอักษรทีละ 1 ตัว",
    "category": "series",
    "pattern": "letter"
  },
  {
    "question": "B  E  H  K  ...",
    "choices": [
      "L",
      "M",
      "N",
      "O"
    ],
    "answer": 2,
    "explanation": "เพิ่มทีละ <strong>3</strong> ตำแหน่ง<br>B → E → H → K → <strong>N</strong>",
    "hint": "นับตำแหน่งตัวอักษร",
    "category": "series",
    "pattern": "letter"
  },
  {
    "question": "Z  X  V  T  ...",
    "choices": [
      "Q",
      "R",
      "S",
      "U"
    ],
    "answer": 1,
    "explanation": "ลดทีละ <strong>2</strong> ตำแหน่ง<br>Z → X → V → T → <strong>R</strong>",
    "hint": "นับถอยหลัง",
    "category": "series",
    "pattern": "letter"
  },
  {
    "question": "W  T  P  M  I  ...",
    "choices": [
      "D",
      "E",
      "F",
      "G"
    ],
    "answer": 2,
    "explanation": "เป็นลำดับตัวอักษรลดลงแบบสลับช่วงตามแนวข้อสอบ<br>คำตอบที่ต่อรูปแบบได้คือ <strong>F</strong>",
    "hint": "ดูตำแหน่งตัวอักษรแบบถอยหลัง",
    "category": "series",
    "pattern": "letter"
  },
  {
    "question": "C  F  J  O  ...",
    "choices": [
      "S",
      "T",
      "U",
      "V"
    ],
    "answer": 2,
    "explanation": "ผลต่างตำแหน่งคือ +3, +4, +5 ดังนั้นถัดไป +6<br>O + 6 = <strong>U</strong>",
    "hint": "ผลต่างเพิ่มขึ้นทีละ 1",
    "category": "series",
    "pattern": "letter"
  },
  {
    "question": "A  B  D  G  K  ...",
    "choices": [
      "N",
      "O",
      "P",
      "Q"
    ],
    "answer": 2,
    "explanation": "ผลต่างตำแหน่งคือ +1, +2, +3, +4 ดังนั้นถัดไป +5<br>K + 5 = <strong>P</strong>",
    "hint": "เพิ่ม 1, 2, 3, 4, ...",
    "category": "series",
    "pattern": "letter"
  },
  {
    "question": "Y  V  S  P  ...",
    "choices": [
      "L",
      "M",
      "N",
      "O"
    ],
    "answer": 1,
    "explanation": "ลดทีละ <strong>3</strong> ตำแหน่ง<br>Y → V → S → P → <strong>M</strong>",
    "hint": "ถอยหลังทีละ 3",
    "category": "series",
    "pattern": "letter"
  },
  {
    "question": "D  H  L  P  ...",
    "choices": [
      "S",
      "T",
      "U",
      "V"
    ],
    "answer": 1,
    "explanation": "เพิ่มทีละ <strong>4</strong> ตำแหน่ง<br>D → H → L → P → <strong>T</strong>",
    "hint": "เพิ่มระยะเท่ากัน",
    "category": "series",
    "pattern": "letter"
  },
  {
    "question": "A  Z  B  Y  C  ...",
    "choices": [
      "W",
      "X",
      "Y",
      "Z"
    ],
    "answer": 1,
    "explanation": "เป็นลำดับสลับหน้า-หลังตัวอักษร<br>A, B, C เพิ่มขึ้น ส่วน Z, Y, <strong>X</strong> ลดลง",
    "hint": "ดูเป็น 2 ชุดสลับกัน",
    "category": "series",
    "pattern": "letter-alternating"
  },
  {
    "question": "M  N  P  S  W  ...",
    "choices": [
      "A",
      "B",
      "C",
      "D"
    ],
    "answer": 1,
    "explanation": "ผลต่างคือ +1, +2, +3, +4 ดังนั้นถัดไป +5<br>W + 5 วนกลับไปได้ <strong>B</strong>",
    "hint": "เพิ่มทีละ 1, 2, 3, 4 แล้ววนตัวอักษร",
    "category": "series",
    "pattern": "letter"
  },
  {
    "question": "1/2  1/4  1/8  1/16  ...",
    "choices": [
      "1/20",
      "1/24",
      "1/32",
      "1/64"
    ],
    "answer": 2,
    "explanation": "ส่วนเพิ่มเป็น 2 เท่าทุกครั้ง<br>2, 4, 8, 16, <strong>32</strong><br>ดังนั้นคำตอบคือ <strong>1/32</strong>",
    "hint": "ดูตัวส่วน",
    "category": "series",
    "pattern": "fraction"
  },
  {
    "question": "2/3  4/6  8/12  16/24  ...",
    "choices": [
      "24/36",
      "32/48",
      "36/54",
      "40/60"
    ],
    "answer": 1,
    "explanation": "ทั้งเศษและส่วนคูณด้วย <strong>2</strong> ทุกครั้ง<br>16×2 = 32 และ 24×2 = 48<br>คำตอบคือ <strong>32/48</strong>",
    "hint": "เศษและส่วนเปลี่ยนพร้อมกัน",
    "category": "series",
    "pattern": "fraction"
  },
  {
    "question": "1/3  2/5  3/7  4/9  ...",
    "choices": [
      "5/10",
      "5/11",
      "6/11",
      "6/13"
    ],
    "answer": 1,
    "explanation": "เศษเพิ่มทีละ 1: 1,2,3,4,<strong>5</strong><br>ส่วนเพิ่มทีละ 2: 3,5,7,9,<strong>11</strong><br>คำตอบคือ <strong>5/11</strong>",
    "hint": "ดูเศษและส่วนแยกกัน",
    "category": "series",
    "pattern": "fraction"
  },
  {
    "question": "3/4  5/7  7/10  9/13  ...",
    "choices": [
      "10/15",
      "11/16",
      "12/17",
      "13/18"
    ],
    "answer": 1,
    "explanation": "เศษเพิ่มทีละ <strong>2</strong>: 3,5,7,9,11<br>ส่วนเพิ่มทีละ <strong>3</strong>: 4,7,10,13,16<br>คำตอบคือ <strong>11/16</strong>",
    "hint": "เศษกับส่วนเพิ่มไม่เท่ากัน",
    "category": "series",
    "pattern": "fraction"
  },
  {
    "question": "4/3  10/7  18/11  28/15  ...",
    "choices": [
      "38/17",
      "40/19",
      "42/19",
      "44/21"
    ],
    "answer": 1,
    "explanation": "เศษเพิ่ม +6, +8, +10 ดังนั้นถัดไป +12 ได้ 28+12 = <strong>40</strong><br>ส่วนเพิ่มทีละ 4: 3,7,11,15,<strong>19</strong><br>คำตอบคือ <strong>40/19</strong>",
    "hint": "ดูผลต่างของเศษและส่วน",
    "category": "series",
    "pattern": "fraction"
  },
  {
    "question": "2/5  4/10  8/20  16/40  ...",
    "choices": [
      "20/60",
      "24/60",
      "32/80",
      "36/90"
    ],
    "answer": 2,
    "explanation": "เศษและส่วนคูณด้วย <strong>2</strong> ทุกครั้ง<br>16×2 = 32 และ 40×2 = 80<br>คำตอบคือ <strong>32/80</strong>",
    "hint": "คูณทั้งเศษและส่วน",
    "category": "series",
    "pattern": "fraction"
  },
  {
    "question": "9/8  18/17  36/19  72/53  ...",
    "choices": [
      "144/91",
      "144/72",
      "288/91",
      "288/107"
    ],
    "answer": 0,
    "explanation": "เศษคูณด้วย <strong>2</strong> ทุกครั้ง: 9,18,36,72,144<br>ส่วนสัมพันธ์จากผลต่างของเศษกับส่วนก่อนหน้าในแนวเดียวกับข้อสอบอนุกรมเศษส่วน ได้ส่วนถัดไปเป็น <strong>91</strong><br>คำตอบคือ <strong>144/91</strong>",
    "hint": "ดูเศษก่อน แล้วค่อยดูส่วน",
    "category": "series",
    "pattern": "fraction"
  },
  {
    "question": "4/3  10/7  18/11  28/15  ...",
    "choices": [
      "35/7",
      "38/11",
      "40/19",
      "40/20"
    ],
    "answer": 2,
    "explanation": "ตัวเศษเพิ่ม +6, +8, +10 ดังนั้นถัดไป +12 ได้ <strong>40</strong><br>ตัวส่วนเพิ่ม +4 ทุกครั้ง ได้ <strong>19</strong><br>คำตอบคือ <strong>40/19</strong>",
    "hint": "เศษเพิ่มทีละเลขคู่ ส่วนเพิ่มทีละ 4",
    "category": "series",
    "pattern": "fraction"
  },
  {
    "question": "1/2  3/4  5/6  7/8  ...",
    "choices": [
      "8/9",
      "9/10",
      "10/11",
      "11/12"
    ],
    "answer": 1,
    "explanation": "เศษเป็นเลขคี่เรียงกัน 1,3,5,7,<strong>9</strong><br>ส่วนเป็นเลขคู่เรียงกัน 2,4,6,8,<strong>10</strong><br>คำตอบคือ <strong>9/10</strong>",
    "hint": "เศษเลขคี่ ส่วนเลขคู่",
    "category": "series",
    "pattern": "fraction"
  },
  {
    "question": "5/4  5  25  150  ...",
    "choices": [
      "650",
      "850",
      "1,040",
      "1,050"
    ],
    "answer": 3,
    "explanation": "เป็นอนุกรมผสมเศษส่วนและจำนวนเต็มตามแนวข้อสอบ<br>5/4 → 5 → 25 → 150 แล้วค่าถัดไปที่สอดคล้องกับชุดคือ <strong>1,050</strong>",
    "hint": "ดูเป็นอนุกรมผสม ไม่ใช่เศษส่วนล้วน",
    "category": "series",
    "pattern": "fraction-mixed"
  }
];
