// AUTO-GENERATED by scripts/migrate-math-games.mjs — DO NOT EDIT
// Source: ~/Documents/SlothMove/Page/source/police_admin/math/math.questions.js (read-only)
// Derived 40 items from the math quiz pool.

import type { QuizItem } from "../../../lib/course-types";

export const math_analogy: QuizItem[] = [
  {
    "question": "ครู : นักเรียน :: แพทย์ : ?",
    "choices": [
      "โรงพยาบาล",
      "คนไข้",
      "พยาบาล",
      "ยา"
    ],
    "answer": 1,
    "explanation": "ครูสอนนักเรียน เช่นเดียวกับแพทย์รักษา <strong>คนไข้</strong>",
    "hint": "ความสัมพันธ์ผู้ปฏิบัติกับผู้รับบริการ",
    "category": "analogy",
    "pattern": "relationship"
  },
  {
    "question": "ปลา : น้ำ :: นก : ?",
    "choices": [
      "ต้นไม้",
      "รัง",
      "อากาศ",
      "ปีก"
    ],
    "answer": 2,
    "explanation": "ปลาอาศัยอยู่ในน้ำ ส่วนนกอาศัยและเคลื่อนที่ใน <strong>อากาศ</strong>",
    "hint": "สถานที่หรือสภาพแวดล้อม",
    "category": "analogy",
    "pattern": "relationship"
  },
  {
    "question": "ปากกา : เขียน :: กรรไกร : ?",
    "choices": [
      "ตัด",
      "พับ",
      "หนีบ",
      "กรีด"
    ],
    "answer": 0,
    "explanation": "ปากกาใช้เขียน กรรไกรใช้ <strong>ตัด</strong>",
    "hint": "เครื่องมือกับหน้าที่",
    "category": "analogy",
    "pattern": "function"
  },
  {
    "question": "หัวใจ : สูบฉีดเลือด :: ปอด : ?",
    "choices": [
      "กรองเลือด",
      "ย่อยอาหาร",
      "แลกเปลี่ยนก๊าซ",
      "สร้างเม็ดเลือด"
    ],
    "answer": 2,
    "explanation": "ปอดทำหน้าที่ <strong>แลกเปลี่ยนก๊าซ</strong>",
    "hint": "อวัยวะกับหน้าที่",
    "category": "analogy",
    "pattern": "function"
  },
  {
    "question": "ร้อน : เย็น :: สูง : ?",
    "choices": [
      "สั้น",
      "ต่ำ",
      "แคบ",
      "เล็ก"
    ],
    "answer": 1,
    "explanation": "ร้อนตรงข้ามเย็น เช่นเดียวกับ สูงตรงข้าม <strong>ต่ำ</strong>",
    "hint": "คำตรงข้าม",
    "category": "analogy",
    "pattern": "opposite"
  },
  {
    "question": "แมว : สัตว์ :: กุหลาบ : ?",
    "choices": [
      "ต้นไม้",
      "ดอกไม้",
      "พืช",
      "สวน"
    ],
    "answer": 1,
    "explanation": "แมวเป็นชนิดหนึ่งของสัตว์ กุหลาบเป็นชนิดหนึ่งของ <strong>ดอกไม้</strong>",
    "hint": "ประเภทและสมาชิก",
    "category": "analogy",
    "pattern": "category"
  },
  {
    "question": "ตำรวจ : จับกุม :: ผู้พิพากษา : ?",
    "choices": [
      "สอบสวน",
      "ตัดสิน",
      "ฟ้องร้อง",
      "คุมขัง"
    ],
    "answer": 1,
    "explanation": "ตำรวจจับกุม ผู้พิพากษา <strong>ตัดสิน</strong>",
    "hint": "อาชีพกับหน้าที่",
    "category": "analogy",
    "pattern": "function"
  },
  {
    "question": "โรงเรียน : นักเรียน :: โรงพยาบาล : ?",
    "choices": [
      "พยาบาล",
      "แพทย์",
      "คนไข้",
      "ยา"
    ],
    "answer": 2,
    "explanation": "โรงเรียนมีนักเรียน โรงพยาบาลมี <strong>คนไข้</strong>",
    "hint": "สถานที่กับผู้ใช้บริการ",
    "category": "analogy",
    "pattern": "relationship"
  },
  {
    "question": "เหล็ก : แข็ง :: ยาง : ?",
    "choices": [
      "เหนียว",
      "อ่อน",
      "ยืดหยุ่น",
      "โปร่งใส"
    ],
    "answer": 2,
    "explanation": "คุณสมบัติเด่นของยางคือ <strong>ยืดหยุ่น</strong>",
    "hint": "วัสดุกับคุณสมบัติ",
    "category": "analogy",
    "pattern": "property"
  },
  {
    "question": "เมล็ด : ต้นไม้ :: ไข่ : ?",
    "choices": [
      "รัง",
      "ลูกไก่",
      "แม่ไก่",
      "ขน"
    ],
    "answer": 1,
    "explanation": "เมล็ดเติบโตเป็นต้นไม้ ไข่ฟักเป็น <strong>ลูกไก่</strong>",
    "hint": "ต้นกำเนิดและผลลัพธ์",
    "category": "analogy",
    "pattern": "growth"
  },
  {
    "question": "กรุงเทพมหานคร : ประเทศไทย :: โตเกียว : ?",
    "choices": [
      "จีน",
      "เกาหลี",
      "ญี่ปุ่น",
      "เวียดนาม"
    ],
    "answer": 2,
    "explanation": "โตเกียวเป็นเมืองหลวงของ <strong>ญี่ปุ่น</strong>",
    "hint": "เมืองหลวงกับประเทศ",
    "category": "analogy",
    "pattern": "relationship"
  },
  {
    "question": "ช้อน : รับประทานอาหาร :: แปรงสีฟัน : ?",
    "choices": [
      "ล้างหน้า",
      "ทำความสะอาดฟัน",
      "หวีผม",
      "โกนหนวด"
    ],
    "answer": 1,
    "explanation": "แปรงสีฟันใช้ <strong>ทำความสะอาดฟัน</strong>",
    "hint": "เครื่องมือกับการใช้งาน",
    "category": "analogy",
    "pattern": "function"
  },
  {
    "question": "น้ำตาล : หวาน :: มะนาว : ?",
    "choices": [
      "ขม",
      "เปรี้ยว",
      "เผ็ด",
      "จืด"
    ],
    "answer": 1,
    "explanation": "มะนาวมีรส <strong>เปรี้ยว</strong>",
    "hint": "สิ่งของกับลักษณะเด่น",
    "category": "analogy",
    "pattern": "property"
  },
  {
    "question": "ฤดูร้อน : ร้อน :: ฤดูหนาว : ?",
    "choices": [
      "ชื้น",
      "แห้ง",
      "หนาว",
      "ฝนตก"
    ],
    "answer": 2,
    "explanation": "ฤดูหนาวมีอากาศ <strong>หนาว</strong>",
    "hint": "ฤดูกับลักษณะเด่น",
    "category": "analogy",
    "pattern": "property"
  },
  {
    "question": "ต้นไม้ : ราก :: อาคาร : ?",
    "choices": [
      "หลังคา",
      "เสาเข็ม",
      "หน้าต่าง",
      "ประตู"
    ],
    "answer": 1,
    "explanation": "รากเป็นฐานของต้นไม้ เช่นเดียวกับ <strong>เสาเข็ม</strong> เป็นฐานของอาคาร",
    "hint": "ส่วนประกอบที่รองรับโครงสร้าง",
    "category": "analogy",
    "pattern": "part-whole"
  },
  {
    "question": "ทนายความ : กฎหมาย :: แพทย์ : ?",
    "choices": [
      "คนไข้",
      "ยา",
      "การแพทย์",
      "โรงพยาบาล"
    ],
    "answer": 2,
    "explanation": "ทนายเกี่ยวข้องกับกฎหมาย แพทย์เกี่ยวข้องกับ <strong>การแพทย์</strong>",
    "hint": "อาชีพกับศาสตร์",
    "category": "analogy",
    "pattern": "relationship"
  },
  {
    "question": "รถยนต์ : ถนน :: เรือ : ?",
    "choices": [
      "สะพาน",
      "แม่น้ำ",
      "ท่าเรือ",
      "ชายฝั่ง"
    ],
    "answer": 1,
    "explanation": "รถยนต์วิ่งบนถนน เรือแล่นใน <strong>แม่น้ำ</strong>",
    "hint": "พาหนะกับเส้นทาง",
    "category": "analogy",
    "pattern": "relationship"
  },
  {
    "question": "หนังสือ : อ่าน :: เพลง : ?",
    "choices": [
      "ร้อง",
      "เต้น",
      "ฟัง",
      "แต่ง"
    ],
    "answer": 2,
    "explanation": "หนังสือใช้สำหรับอ่าน เพลงใช้สำหรับ <strong>ฟัง</strong>",
    "hint": "สิ่งของกับกิจกรรม",
    "category": "analogy",
    "pattern": "function"
  },
  {
    "question": "วัน : สัปดาห์ :: เดือน : ?",
    "choices": [
      "ปี",
      "ศตวรรษ",
      "ชั่วโมง",
      "นาที"
    ],
    "answer": 0,
    "explanation": "วันรวมกันเป็นสัปดาห์ เดือนรวมกันเป็น <strong>ปี</strong>",
    "hint": "หน่วยเวลา",
    "category": "analogy",
    "pattern": "relationship"
  },
  {
    "question": "นักฟุตบอล : สนามฟุตบอล :: นักว่ายน้ำ : ?",
    "choices": [
      "ทะเล",
      "แม่น้ำ",
      "สระว่ายน้ำ",
      "อ่างเก็บน้ำ"
    ],
    "answer": 2,
    "explanation": "นักฟุตบอลเล่นในสนามฟุตบอล นักว่ายน้ำแข่งขันใน <strong>สระว่ายน้ำ</strong>",
    "hint": "อาชีพ/กิจกรรมกับสถานที่",
    "category": "analogy",
    "pattern": "relationship"
  },
  {
    "question": "ร่ม : กันฝน :: หมวกกันน็อก : ?",
    "choices": [
      "กันแดด",
      "กันกระแทก",
      "กันหนาว",
      "กันเสียง"
    ],
    "answer": 1,
    "explanation": "ร่มใช้กันฝน ส่วนหมวกกันน็อกใช้ <strong>กันกระแทก</strong> หรือป้องกันศีรษะ",
    "hint": "สิ่งของกับหน้าที่ป้องกัน",
    "category": "analogy",
    "pattern": "function"
  },
  {
    "question": "สวิง : กุ้ง :: แห : ?",
    "choices": [
      "ปลา",
      "นก",
      "ปู",
      "หอย"
    ],
    "answer": 0,
    "explanation": "สวิงใช้ช้อนจับกุ้ง ส่วนแหมักใช้จับ <strong>ปลา</strong>",
    "hint": "เครื่องมือกับสิ่งที่จับ",
    "category": "analogy",
    "pattern": "function"
  },
  {
    "question": "เรือดำน้ำ : ปลา :: เครื่องบิน : ?",
    "choices": [
      "นก",
      "เมฆ",
      "ลม",
      "ท้องฟ้า"
    ],
    "answer": 0,
    "explanation": "เรือดำน้ำเคลื่อนที่ในน้ำคล้ายปลา เครื่องบินบินบนอากาศคล้าย <strong>นก</strong>",
    "hint": "สิ่งประดิษฐ์เปรียบกับสิ่งมีชีวิต",
    "category": "analogy",
    "pattern": "relationship"
  },
  {
    "question": "เชิงเทียน : เทียนไข :: แจกัน : ?",
    "choices": [
      "น้ำ",
      "ดอกไม้",
      "โต๊ะ",
      "แก้ว"
    ],
    "answer": 1,
    "explanation": "เชิงเทียนใช้ตั้งเทียนไข แจกันใช้ปัก <strong>ดอกไม้</strong>",
    "hint": "ภาชนะ/ที่วางกับสิ่งที่ใส่",
    "category": "analogy",
    "pattern": "function"
  },
  {
    "question": "ครู : สอน :: ตำรวจ : ?",
    "choices": [
      "รักษา",
      "จับผู้ร้าย",
      "ค้าขาย",
      "ก่อสร้าง"
    ],
    "answer": 1,
    "explanation": "ครูมีหน้าที่สอน ตำรวจมีหน้าที่ <strong>จับผู้ร้าย</strong>",
    "hint": "อาชีพกับหน้าที่",
    "category": "analogy",
    "pattern": "function"
  },
  {
    "question": "สัดส่วน : ร้อยละ :: โคลง : ?",
    "choices": [
      "เรื่องสั้น",
      "บทความ",
      "กลอน",
      "นิยาย"
    ],
    "answer": 2,
    "explanation": "สัดส่วนมีความสัมพันธ์ใกล้เคียงกับร้อยละ ในทำนองเดียวกันโคลงเป็นคำประพันธ์เช่นเดียวกับ <strong>กลอน</strong>",
    "hint": "คำที่อยู่ในกลุ่มความหมายใกล้กัน",
    "category": "analogy",
    "pattern": "meaning"
  },
  {
    "question": "ประจิม : ตะวันตก :: บูรพา : ?",
    "choices": [
      "เหนือ",
      "ใต้",
      "ตะวันออก",
      "ตะวันตก"
    ],
    "answer": 2,
    "explanation": "ประจิมหมายถึงทิศตะวันตก ส่วนบูรพาหมายถึง <strong>ทิศตะวันออก</strong>",
    "hint": "คำโบราณเกี่ยวกับทิศ",
    "category": "analogy",
    "pattern": "meaning"
  },
  {
    "question": "อุดร : เหนือ :: ทักษิณ : ?",
    "choices": [
      "ใต้",
      "ออก",
      "ตก",
      "กลาง"
    ],
    "answer": 0,
    "explanation": "อุดรหมายถึงทิศเหนือ ทักษิณหมายถึง <strong>ทิศใต้</strong>",
    "hint": "คำบอกทิศ",
    "category": "analogy",
    "pattern": "meaning"
  },
  {
    "question": "เล็บ : นิ้ว :: ผม : ?",
    "choices": [
      "หน้า",
      "ศีรษะ",
      "คอ",
      "ไหล่"
    ],
    "answer": 1,
    "explanation": "เล็บอยู่ที่นิ้ว ผมอยู่บน <strong>ศีรษะ</strong>",
    "hint": "ส่วนย่อยกับตำแหน่ง",
    "category": "analogy",
    "pattern": "part-whole"
  },
  {
    "question": "ปอด : หายใจ :: กระเพาะอาหาร : ?",
    "choices": [
      "สูบฉีดเลือด",
      "ย่อยอาหาร",
      "กรองเลือด",
      "รับเสียง"
    ],
    "answer": 1,
    "explanation": "ปอดเกี่ยวกับการหายใจ กระเพาะอาหารเกี่ยวกับการ <strong>ย่อยอาหาร</strong>",
    "hint": "อวัยวะกับหน้าที่",
    "category": "analogy",
    "pattern": "function"
  },
  {
    "question": "มะระ : ขม :: ลำไย : ?",
    "choices": [
      "เปรี้ยว",
      "หวาน",
      "เค็ม",
      "เผ็ด"
    ],
    "answer": 1,
    "explanation": "มะระมีรสขม ลำไยมักมีรส <strong>หวาน</strong>",
    "hint": "อาหาร/ผลไม้กับรสชาติ",
    "category": "analogy",
    "pattern": "property"
  },
  {
    "question": "สะพาน : ข้าม :: บันได : ?",
    "choices": [
      "ปีน",
      "นั่ง",
      "นอน",
      "ว่าย"
    ],
    "answer": 0,
    "explanation": "สะพานใช้สำหรับข้าม บันไดใช้สำหรับ <strong>ปีน</strong> หรือขึ้นลง",
    "hint": "สิ่งก่อสร้างกับการใช้งาน",
    "category": "analogy",
    "pattern": "function"
  },
  {
    "question": "ตา : มองเห็น :: หู : ?",
    "choices": [
      "ดมกลิ่น",
      "ฟังเสียง",
      "รับรส",
      "สัมผัส"
    ],
    "answer": 1,
    "explanation": "ตาใช้มองเห็น หูใช้ <strong>ฟังเสียง</strong>",
    "hint": "อวัยวะรับสัมผัส",
    "category": "analogy",
    "pattern": "function"
  },
  {
    "question": "มีด : หั่น :: เข็ม : ?",
    "choices": [
      "เย็บ",
      "ตัด",
      "ทุบ",
      "ขุด"
    ],
    "answer": 0,
    "explanation": "มีดใช้หั่น เข็มใช้ <strong>เย็บ</strong>",
    "hint": "เครื่องมือกับการกระทำ",
    "category": "analogy",
    "pattern": "function"
  },
  {
    "question": "นาฬิกา : เวลา :: เครื่องชั่ง : ?",
    "choices": [
      "ระยะทาง",
      "น้ำหนัก",
      "อุณหภูมิ",
      "ความเร็ว"
    ],
    "answer": 1,
    "explanation": "นาฬิกาใช้วัดเวลา เครื่องชั่งใช้วัด <strong>น้ำหนัก</strong>",
    "hint": "เครื่องมือวัดกับสิ่งที่วัด",
    "category": "analogy",
    "pattern": "function"
  },
  {
    "question": "ตาชั่ง : น้ำหนัก :: เทอร์โมมิเตอร์ : ?",
    "choices": [
      "เวลา",
      "ความสูง",
      "อุณหภูมิ",
      "ความเร็ว"
    ],
    "answer": 2,
    "explanation": "ตาชั่งวัดน้ำหนัก เทอร์โมมิเตอร์วัด <strong>อุณหภูมิ</strong>",
    "hint": "เครื่องมือวัด",
    "category": "analogy",
    "pattern": "function"
  },
  {
    "question": "ขาว : ดำ :: กลางวัน : ?",
    "choices": [
      "เช้า",
      "เย็น",
      "กลางคืน",
      "สว่าง"
    ],
    "answer": 2,
    "explanation": "ขาวตรงข้ามดำ กลางวันตรงข้าม <strong>กลางคืน</strong>",
    "hint": "คำตรงข้าม",
    "category": "analogy",
    "pattern": "opposite"
  },
  {
    "question": "ขยัน : เกียจคร้าน :: ซื่อสัตย์ : ?",
    "choices": [
      "ฉลาด",
      "ทุจริต",
      "อดทน",
      "กล้าหาญ"
    ],
    "answer": 1,
    "explanation": "ขยันตรงข้ามเกียจคร้าน ซื่อสัตย์ตรงข้าม <strong>ทุจริต</strong>",
    "hint": "หาคำตรงข้าม",
    "category": "analogy",
    "pattern": "opposite"
  },
  {
    "question": "เมฆ : ฝน :: ควัน : ?",
    "choices": [
      "ไฟ",
      "น้ำ",
      "ลม",
      "ดิน"
    ],
    "answer": 0,
    "explanation": "ฝนสัมพันธ์กับเมฆ ส่วนควันสัมพันธ์กับ <strong>ไฟ</strong>",
    "hint": "เหตุและผลหรือสิ่งที่มักเกิดร่วมกัน",
    "category": "analogy",
    "pattern": "cause-effect"
  },
  {
    "question": "ดินสอ : ยางลบ :: คำผิด : ?",
    "choices": [
      "ปากกา",
      "สมุด",
      "การแก้ไข",
      "ไม้บรรทัด"
    ],
    "answer": 2,
    "explanation": "ยางลบใช้ลบรอยดินสอ คำผิดต้องได้รับ <strong>การแก้ไข</strong>",
    "hint": "สิ่งที่ใช้แก้ข้อผิดพลาด",
    "category": "analogy",
    "pattern": "relationship"
  }
];
