// AUTO-GENERATED by scripts/migrate-industry.mjs
// Re-exports all migrated subject data for type-safe imports.

export * from './admin_act';
export * from './factory_act';
export * from './info_act';
export * from './governance';
export * from './industrial_strategy';
