// AUTO-GENERATED by scripts/migrate-pab.mjs
// Re-exports all subject data for type-safe imports.

export * from './admin_act';
export * from './info_act';
export * from './civil_service_act';
export * from './saraban_regulation';
export * from './budget_act';
export * from './disaster_act';
export * from './volunteer_regulation';
export * from './policy_analysis';
export * from './warning_regulation';
export * from './national_accident_regulation';
export * from './national_disaster_plan';
export * from './ministry_act';
export * from './disaster_situation';
export * from './disaster_department';
export * from './emergency_fund_regulation';
export * from './budget_knowledge';
export * from './english';
export * from './political_economy';
export * from './national_plan';
export * from './road_safety_regulation';

// Curated datasets (manual, not auto-migrated)
export { PAB_AUTHORITY } from './authority';
export { PAB_LOGIC } from './logic';
