/**
 * PAB Data Loader — reads auto-generated TypeScript modules
 *
 * Data is auto-generated by scripts/migrate-pab.mjs from
 * ~/Documents/SlothMove/Page/source/PAB/ (READ-ONLY).
 *
 * For games whose data hasn't been migrated yet (sorting, order,
 * spelling, truefalse), we return a small set of universal sample
 * items so the games are testable end-to-end.
 *
 * Authority/Logic now use per-subject curated data only. If a subject
 * has no curated entries yet, the loader returns [] so the UI can show
 * an honest "ยังไม่มีข้อมูล" state instead of a misleading fallback.
 *
 * To add new subjects: extend SUBJECTS in the script, then re-run.
 *   cd slothmove-platform && node scripts/migrate-pab.mjs
 */

import * as PABData from './data';
import type { CourseConfig, GameId } from '@/lib/course-types';
import { PAB_AUTHORITY, PAB_LOGIC } from './data';

type PABModule = { [k: string]: any };
const PAB_MODULES = PABData as PABModule;

/* -------------------------------------------------------------------------- */
/*                       Sample data for non-migrated games                   */
/* -------------------------------------------------------------------------- */

const SAMPLE_SORTING = [
  {
    question: 'เรียงลำดับหน่วยงานตามลำดับการบังคับบัญชาจากบนลงล่าง',
    items: [
      'นายกรัฐมนตรี',
      'รัฐมนตรี',
      'ปลัดกระทรวง',
      'อธิบดี',
      'หัวหน้ากอง'
    ],
    explain: 'โครงสร้างการบังคับบัญชาในระบบราชการไทย เริ่มจากนายกรัฐมนตรี → รัฐมนตรี → ปลัดกระทรวง → อธิบดี → หัวหน้ากอง'
  },
  {
    question: 'เรียงลำดับขั้นตอนการจัดทำงบประมาณแผ่นดิน',
    items: [
      'ส่วนราชการจัดทำคำขอ',
      'สำนักงบประมาณพิจารณา',
      'ครม.อนุมัติ',
      'สภาผู้แทนฯพิจารณา',
      'พระราชทานพระบรมราชานุญาต',
      'ประกาศใช้บังคับ'
    ],
    explain: 'ขั้นตอนตาม พ.ร.บ. วิธีการงบประมาณ'
  }
];

const SAMPLE_ORDER = [
  {
    question: 'เรียงขั้นตอนการรับหนังสือราชการ',
    steps: [
      'รับหนังสือจากหน่วยงานภายนอก',
      'ลงทะเบียนรับ',
      'เสนอผู้บังคับบัญชา',
      'สั่งการ/พิจารณา',
      'ดำเนินการตามคำสั่ง',
      'จัดเก็บเข้าแฟ้ม'
    ],
    explain: 'ขั้นตอนตามระเบียบงานสารบรรณ'
  },
  {
    question: 'เรียงขั้นตอนการประกาศใช้พระราชบัญญัติ',
    steps: [
      'สภาผู้แทนฯ พิจารณา',
      'วุฒิสภาพิจารณา',
      'นายกรัฐมนตรีนำขึ้นทูลเกล้าฯ',
      'พระมหากษัตริย์ทรงลงพระปรมาภิไธย',
      'ประกาศในราชกิจจานุเบกษา',
      'มีผลบังคับใช้'
    ]
  }
];

const SAMPLE_SPELLING = [
  { word: 'มหาดไทย', definition: 'ชื่อกระทรวงที่ดูแลเรื่องท้องถิ่น', hint: 'ขึ้นต้นด้วย ม' },
  { word: 'สาธารณภัย', definition: 'ภัยที่เกิดขึ้นต่อสาธารณะ เช่น น้ำท่วม', hint: 'มีคำว่า "ภัย" อยู่ข้างหลัง' },
  { word: 'ข้าราชการ', definition: 'ผู้ที่ทำงานในระบบราชการ', hint: 'เริ่มด้วย ข' },
  { word: 'อำเภอ', definition: 'เขตปกครองระดับหนึ่งของจังหวัด', hint: 'มี 4 พยางค์' }
];

const SAMPLE_TRUEFALSE = [
  { statement: 'พ.ร.บ. ระเบียบบริหารราชการแผ่นดิน พ.ศ. 2534 มีผลใช้บังคับตั้งแต่วันประกาศในราชกิจจานุเบกษา', answer: false, explain: 'จริง ๆ มีผลใช้บังคับตั้งแต่วันถัดจากวันประกาศในราชกิจจานุเบกษา' },
  { statement: 'การบริหารราชการแผ่นดินแบ่งออกเป็น 4 ส่วน', answer: false, explain: 'แบ่งเป็น 3 ส่วน: ส่วนกลาง ส่วนภูมิภาค ส่วนท้องถิ่น' },
  { statement: 'ผู้ว่าราชการจังหวัดเป็นหัวหน้าราชการประจำจังหวัด', answer: true },
  { statement: 'เทศบาลเป็นหน่วยงานของรัฐวิสาหกิจ', answer: false, explain: 'เทศบาลเป็นองค์กรปกครองส่วนท้องถิ่น ไม่ใช่รัฐวิสาหกิจ' }
];

const SAMPLE_AUTHORITY: never[] = [];
/**
 * Authority/Logic: per-subject curated data only.
 *
 * Coverage (Phase C audit):
 *   - PAB_AUTHORITY : curated for 12/20 subjects
 *   - PAB_LOGIC     : curated for 6/20 subjects
 *
 * Behavior:
 *   - If `subjectId` has its own curated array → use it.
 *   - Otherwise → return [] so the game page renders NoDataView with an
 *     honest "ยังไม่มีข้อมูล" message for that subject.
 */

/* -------------------------------------------------------------------------- */
/*                            getSubjectData (main API)                       */
/* -------------------------------------------------------------------------- */

export function getSubjectData(
  course: CourseConfig,
  subjectId: string,
  game: GameId
): any[] {
  if (course.id !== 'pab') return [];

  // Quiz + flashcard + match + cloze: data is auto-migrated from PAB
  // Quiz → Match/Cloze uses src/lib/adapters/quiz-to-games.ts at migration time
  if (game === 'quiz' || game === 'flashcard' || game === 'match' || game === 'cloze') {
    const moduleData = PAB_MODULES[`${subjectId}_${game}`];
    if (!moduleData || !Array.isArray(moduleData)) return [];
    if (game === 'flashcard') {
      return moduleData.map((c: any) => ({ front: String(c.front || ''), back: String(c.back || '') }));
    }
    // quiz / match / cloze — shape already matches the shared types
    return moduleData;
  }

  // Sorting, Order, Spelling, TrueFalse: return universal samples
  // (Phase 2.4) until per-subject data is migrated.
  // Authority, Logic: per-subject curated data from ./authority + ./logic.
  switch (game) {
    case 'sorting': return SAMPLE_SORTING;
    case 'order': return SAMPLE_ORDER;
    case 'spelling': return SAMPLE_SPELLING;
    case 'truefalse': return SAMPLE_TRUEFALSE;
    case 'authority': {
      const subjectPairs = PAB_AUTHORITY[subjectId];
      if (subjectPairs && subjectPairs.length > 0) return subjectPairs;
      // Phase C fix: NO fallback. If this subject has no curated pairs,
      // return [] so the game page renders "ยังไม่มีข้อมูล หน่วยงาน"
      // instead of pretending the user is studying admin_act while on
      // another subject. Truthful per-subject.
      return [];
    }
    case 'logic': {
      const subjectItems = PAB_LOGIC[subjectId];
      if (subjectItems && subjectItems.length > 0) return subjectItems;
      // Phase C fix: NO fallback to 'default'. Same reasoning as authority —
      // the 'default' set is a logic puzzle collection, not subject-specific.
      // Returning [] gives the honest "ยังไม่มีข้อมูล" message.
      return [];
    }
    default:
      // 'quiz' | 'flashcard' | 'match' | 'cloze' are handled above.
      return [];
  }
}

export function getSubjectItemCount(subjectId: string, game: GameId): number {
  if (game === 'quiz' || game === 'flashcard' || game === 'match' || game === 'cloze') {
    const data = PAB_MODULES[`${subjectId}_${game}`];
    return Array.isArray(data) ? data.length : 0;
  }
  // Authority/Logic: count = curated items for THIS subject, or 0 if none.
  // Do NOT inflate with admin_act/default fallback counts — they don't
  // belong to the requested subject (Phase C fix).
  if (game === 'authority') {
    const data = PAB_AUTHORITY[subjectId];
    return data?.length ?? 0;
  }
  if (game === 'logic') {
    const data = PAB_LOGIC[subjectId];
    return data?.length ?? 0;
  }
  // Sample sizes for non-migrated games
  const SAMPLE_SIZES: Partial<Record<GameId, number>> = {
    sorting: 2, order: 2, spelling: 4, truefalse: 4
  };
  return SAMPLE_SIZES[game] ?? 0;
}
